use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'LZDependencyControlkit_Example' do
  pod 'LZDependencyControlkit', :path => '../'

  target 'LZDependencyControlkit_Tests' do
    inherit! :search_paths
  end
end
