use_frameworks!

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'LZDependencyControlkit_Example' do
  pod 'LZDependencyControlkit', :path => '../'

  target 'LZDependencyControlkit_Tests' do
    inherit! :search_paths
  end
end
